import ast
from pathlib import Path
from datetime import datetime
from buster.agents.base import Agent

WEATHER_MAIN = 'import tkinter as tk\nfrom tkinter import ttk\nfrom config import APP_NAME\n\nclass WeatherApp(tk.Tk):\n    def __init__(self):\n        super().__init__()\n        self.title(APP_NAME)\n        self.geometry("420x260")\n        self.resizable(False, False)\n        ttk.Label(self, text=APP_NAME, font=("Segoe UI", 18, "bold")).pack(pady=16)\n        frame = ttk.Frame(self)\n        frame.pack(pady=8)\n        ttk.Label(frame, text="City:").grid(row=0, column=0, padx=6, pady=6)\n        self.city = ttk.Entry(frame, width=28)\n        self.city.grid(row=0, column=1, padx=6, pady=6)\n        self.city.insert(0, "Melbourne")\n        ttk.Button(self, text="Check Weather", command=self.check_weather).pack(pady=10)\n        self.output = ttk.Label(self, text="Enter a city and click Check Weather.", wraplength=360)\n        self.output.pack(pady=10)\n\n    def check_weather(self):\n        city = self.city.get().strip() or "your city"\n        self.output.config(text=f"Weather lookup scaffold for {city}. Add an API provider next.")\n\nif __name__ == "__main__":\n    WeatherApp().mainloop()\n'
BASIC_MAIN = 'import tkinter as tk\nfrom tkinter import ttk\nfrom config import APP_NAME\n\nclass App(tk.Tk):\n    def __init__(self):\n        super().__init__()\n        self.title(APP_NAME)\n        self.geometry("420x260")\n        ttk.Label(self, text=APP_NAME, font=("Segoe UI", 18, "bold")).pack(pady=20)\n        ttk.Label(self, text="Generated by Buster Builder Agent.").pack(pady=10)\n\nif __name__ == "__main__":\n    App().mainloop()\n'

class BuilderAgent(Agent):
    name = "builder"

    def run(self, task):
        self.current_task = task
        self.status = "Running"
        self.progress = 10
        project_name = self._project_name(task)
        project_root = Path("buster_workspace/projects") / project_name
        project_root.mkdir(parents=True, exist_ok=True)
        files = self._generate_project(task, project_name)
        written = []
        for rel, content in files.items():
            path = project_root / rel
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            written.append(str(path))
            self.progress = min(90, self.progress + 10)
        syntax = self._check_python(project_root)
        self.progress = 100
        self.status = "Done"
        return "Builder created project: " + str(project_root) + "\nFiles written: " + str(len(written)) + "\n" + "\n".join(["- " + p for p in written]) + "\n\n" + syntax

    def _project_name(self, task):
        name = task.lower()
        for word in ["create", "make", "build", "app", "project", "a", "an", "the"]:
            name = name.replace(word, " ")
        name = "_".join(name.split())[:40] or "buster_project"
        return name + "_" + datetime.now().strftime("%Y%m%d_%H%M%S")

    def _generate_project(self, task, project_name):
        title = project_name.replace("_", " ").title()
        main_code = WEATHER_MAIN if "weather" in task.lower() else BASIC_MAIN
        return {
            "README.md": "# " + title + "\n\nGenerated by Buster Builder Agent.\n\nTask: " + task + "\n\nRun:\n\n```bat\npython main.py\n```\n",
            "requirements.txt": "",
            "config.py": 'APP_NAME = "' + title + '"\nVERSION = "1.0.0"\n',
            "main.py": main_code,
            "tests.py": "import ast\nfrom pathlib import Path\n\nfor file in Path('.').glob('*.py'):\n    ast.parse(file.read_text(encoding='utf-8'))\nprint('syntax ok')\n",
        }

    def _check_python(self, project_root):
        errors = []
        for path in project_root.glob("*.py"):
            try:
                ast.parse(path.read_text(encoding="utf-8"))
            except Exception as exc:
                errors.append(path.name + ": " + str(exc))
        return "Syntax check failed:\n" + "\n".join(errors) if errors else "Syntax check passed."
